import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Store</title>
        <meta name="description" content="Generated by Platzi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 class="text-3xl font-bold underline">Hello world!</h1>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
